<?php
define('TJLOTTO', 'TJLOTTO');             //天津時時彩
define('XJLOTTO', 'XJLOTTO');             //新疆時時彩
define('CQLOTTO', 'CQLOTTO');             //重慶時時彩
define('BJPK10', 'BJPK10');               //北京PK10
define('BINGO', 'BINGO');                 //賓果賓果
define('BJHAPPY8', 'BJHAPPY8');           //北京快樂8
define('SPEEDCAR', 'SPEEDCAR');           //極速賽車
define('WELFARE3D', 'WELFARE3D');         //福彩3D
define('LUCKYAIRSHIP', 'LUCKYAIRSHIP');   //幸運飛艇
define('GUANGDONG', 'GUANGDONG');         //廣東11選5
define('XINJIANG', 'XINJIANG');           //新疆11選5
define('SHANGHAI', 'SHANGHAI');           //上海11選5
define('SHANDONG', 'SHANDONG');           //山東11選5
define('JIANGXI', 'JIANGXI');             //江西11選5
define('BEIJINGF3', 'BEIJINGF3');         //北京快3
define('JIANGSUF3', 'JIANGSUF3');         //江蘇快3
define('GUANGXIF3', 'GUANGXIF3');         //廣西快3
define('JILINF3', 'JILINF3');             //吉林快3
define('HENANF3', 'HENANF3');             //河南快3
define('AUSTRALIA5', 'AUSTRALIA5');       //澳洲幸運5
define('SGAIRSHIP', 'SGAIRSHIP');         //SG飛艇
define('AUSTRALIA10', 'AUSTRALIA10');     //澳洲幸運10
